# Generated by Django 3.0.1 on 2020-01-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Booking_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Booking_seat', models.CharField(max_length=4)),
                ('Booking_showTime', models.DateTimeField()),
                ('Booking_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Booking_ticketCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('Cinema_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Cinema_address', models.CharField(blank=True, max_length=50)),
                ('Cinema_email', models.EmailField(max_length=50)),
                ('Cinema_admin', models.CharField(default='Admin', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_name', models.CharField(max_length=30)),
                ('Customer_email', models.EmailField(max_length=50)),
                ('Customer_contactNo', models.IntegerField()),
                ('Customer_address', models.CharField(blank=True, max_length=50)),
                ('Customer_password', models.CharField(max_length=30)),
                ('Customer_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Movie_title', models.CharField(max_length=30)),
                ('Movie_License', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Movie_genre', models.CharField(max_length=30)),
                ('Movie_releaseDate', models.DateField(editable=False)),
                ('Movie_finalShowDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_id', models.CharField(max_length=9, primary_key=2, serialize=False)),
                ('Payment_totalPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Payment_date', models.DateTimeField()),
                ('Booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Booking')),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='Customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Movie'),
        ),
    ]
