# Generated by Django 3.0.1 on 2020-01-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Booking_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Booking_seat', models.CharField(max_length=4)),
                ('Booking_showTime', models.DateTimeField()),
                ('Booking_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Booking_ticketCount', models.IntegerField()),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Movie_title', models.CharField(max_length=30)),
                ('Movie_License', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Movie_genre', models.CharField(max_length=30)),
                ('Movie_releaseDate', models.DateField(editable=False)),
                ('Movie_finalShowDate', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='Cinema_admin',
            field=models.CharField(default='Admin', max_length=30),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_id', models.CharField(max_length=9, primary_key=2, serialize=False)),
                ('Payment_totalPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Payment_date', models.DateTimeField()),
                ('Booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Booking')),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='Movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movie'),
        ),
    ]
