# Generated by Django 3.0.1 on 2020-02-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_title', models.CharField(max_length=30)),
                ('Movie_genre', models.CharField(max_length=30)),
                ('Movie_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
