# Generated by Django 3.0.1 on 2020-02-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Movir_image',
            field=models.ImageField(blank=True, null=True, upload_to='movies/images'),
        ),
    ]
