# Generated by Django 3.0.1 on 2020-02-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_movie_movir_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Movir_image',
            new_name='Movie_image',
        ),
    ]
