# Generated by Django 3.0.1 on 2020-02-10 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200209_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Firstname', models.CharField(max_length=30)),
                ('Customer_Lastname', models.CharField(max_length=30)),
                ('Customer_Username', models.CharField(max_length=30)),
                ('Customer_email', models.EmailField(max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_ticketCount', models.IntegerField()),
                ('Booking_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Customer_Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Customer')),
                ('Movie_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Movie')),
            ],
        ),
    ]
