# Generated by Django 3.0.1 on 2020-02-10 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_booking_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='movie',
        ),
    ]
