# Generated by Django 3.0.1 on 2020-02-10 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_customer_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Movie_title',
            field=models.ForeignKey(default='movie', on_delete=django.db.models.deletion.CASCADE, to='Home.Movie'),
        ),
    ]
