# Generated by Django 3.0.1 on 2020-02-10 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20200210_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Movie'),
        ),
    ]
